name: HTML Translation Pipeline

on:
  workflow_dispatch:
    inputs:
      target_lang:
        description: 'Target language code (e.g. fr)'
        required: true
        default: 'fr'

env:
  PYTHON_VERSION: '3.10'
  TARGET_LANG: ${{ github.event.inputs.target_lang }}
  DEEPL_KEY: ${{ secrets.DEEPL_KEY }}
  CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests inquirer

      - name: Run translation script
        run: |
          python translator_fixed.py
        env:
          CI: 'true'
          TARGET_LANG: ${{ env.TARGET_LANG }}
          DEEPL_KEY: ${{ env.DEEPL_KEY }}
          CHATGPT_KEY: ${{ env.CHATGPT_KEY }}

      - name: Upload translated HTML files
        uses: actions/upload-artifact@v4
        with:
          name: translated-files
          path: "*-*.html"
