name: HTML Translation Pipeline

on:
  workflow_dispatch:
    inputs:
      target_lang:
        description: 'Target language code (e.g. fr)'
        required: true
        default: 'fr'

env:
  PYTHON_VERSION: '3.10'
  DEEPL_KEY: ${{ secrets.DEEPL_KEY }}
  LIBRE_URLS: ${{ secrets.LIBRE_URLS }}
  CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 inquirer requests beautifulsoup4
        pip freeze  # Verify installed packages

    - name: Validate HTML files
      run: |
        echo "📋 Repository files:"
        find . -name "*.html" -exec ls -la {} \;
        echo "🔍 Valid HTML files found:"
        python -c "
        from bs4 import BeautifulSoup
        from pathlib import Path
        for f in Path('.').rglob('*.html'):
            try:
                BeautifulSoup(f.read_text(), 'html.parser')
                print(f'✓ {f}')
            except Exception as e:
                print(f'✗ {f} (Invalid HTML: {str(e)})')
        "

    - name: Run translation
      run: |
        python translator.py
      env:
        DEEPL_KEY: ${{ env.DEEPL_KEY }}
        LIBRE_URLS: ${{ env.LIBRE_URLS }}
        CHATGPT_KEY: ${{ env.CHATGPT_KEY }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: translated-files
        path: '*-*.html'
