name: HTML Translation Pipeline

on:
  workflow_dispatch:
    inputs:
      target_lang:
        description: 'Target language code (e.g. fr)'
        required: true
        default: 'fr'

env:
  PYTHON_VERSION: '3.10'
  DEEPL_KEY: ${{ secrets.DEEPL_KEY }}
  LIBRE_URLS: ${{ secrets.LIBRE_URLS }}
  CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
  EXCLUDED_LANG_SUFFIXES: 'fr,es,de'  # Matches EXCLUDED_LANG_SUFFIXES in Python

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install inquirer requests beautifulsoup4

    - name: Run translation
      run: |
        python translator.py
      env:
        DEEPL_KEY: ${{ env.DEEPL_KEY }}
        LIBRE_URLS: ${{ env.LIBRE_URLS }}
        CHATGPT_KEY: ${{ env.CHATGPT_KEY }}
        TARGET_LANG: ${{ inputs.target_lang }}  # Passes to get_target_language()

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: translated-files
        path: '*-*.html'  # Matches output_file pattern in Python
